openapi: 3.0.0
info:
  version: KatalogAPIVKB3
  title: KatalogAPIVKB3
  description: KatalogAPIVKB3
paths: 

  /artikel/:
    get:
      tags:
        - Shop
      summary: Gebe alle Artikel
      description: Liefert alle Artikel zurück
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artikel'
    post:
      tags:
        - Shop
      summary: Lege einen Artikel an
      description: Mit diesem Endpunkt wird ein Artikel angelegt
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artikel'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Artikel'

  /artikel/{aid}:
    parameters:
      - in: path
        name: aid
        schema:
          type: string
        required: true
    get:
      tags:
        - Shop
      summary: Gebe einen Artikel zurück
      description: Liefert einen Artikel aufgrund der aid zurück
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Artikel'
    
    
components:
  schemas:
    Artikel:
      properties:
        id:
          type: string
          format: uuid     
        name:
          type: string
          maxLength: 20
          example: HansWurst
          description: Dies ist der Name des Artikels
        preis:
          type: number
          minimum: 0
          example: 3.99
          description: Dies ist der Preis des Artikels
