stages:
  - build
  - package
  - deploy

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 1
  GIT_URL: "https://github.com/andymaier/spring-boot-codegenerator"
  GIT_BRANCH: "master"
  IMAGE_NAME: registry.ocp4.de/andymaier/catalog
  IMAGE_TAG: $CI_COMMIT_SHA

before_script:
  - git clone --branch $GIT_BRANCH $GIT_URL

build:
  stage: build
  script:
    - mvn test
    - mvn package

package:
  stage: package
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  script:
    - scp docker-compose.yml azureuser@catalog.ocp4.de:/home/azureuser/catalog/docker-compose.yml
    - ssh azureuser@catalog.ocp4.de "docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY"
    - ssh azureuser@catalog.ocp4.de "docker pull $IMAGE_NAME:$IMAGE_TAG"
    - ssh azureuser@catalog.ocp4.de "docker-compose up -d"
    - ssh -t azureuser@catalog.ocp4.de "cd /home/azureuser/catalog/ && docker-compose up -d"