version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: artikel
      POSTGRES_USER: artikel
    networks:
      - catalogueNetwork
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8089:8080
    depends_on:
      - db
    networks:
      - catalogueNetwork

networks:
  catalogueNetwork:
    driver: bridge